In [9]:
# 1- Qual a média do preço de compra dos imóveis por nível?
# Nível 0 --> Preço entre R$ 0 e R$ 321950
# Nível 1 --> Preço entre R$ 321950 e R$ 450000
# Nível 2 --> Preço entre R$ 450000 e R$ 645000
# Nível 3 --> Acima de R$ 645000

import pandas as pd

data = pd.read_csv('datasets/kc_house_data.csv')

data['level'] = 'NA'


for i in range(len(data)):
    
    if (data.loc[i, 'price'] > 0) & (data.loc[i, 'price'] <= 321950):
        data.loc[i, 'level'] = 'Level 0'
        
    elif (data.loc[i, 'price'] > 321950) & (data.loc[i, 'price'] <= 450000):
         data.loc[i, 'level'] = 'Level 1'
            
    elif (data.loc[i, 'price'] > 450000) & (data.loc[i, 'price'] <= 645000):
         data.loc[i, 'level'] = 'Level 2'
            
    else:
        data.loc[i, 'level'] = 'Level 3'
        
by_price = data[['price', 'level']].groupby('level').mean().reset_index()
print(by_price)

     level          price
0  Level 0  251557.649889
1  Level 1  385688.681502
2  Level 2  539730.960007
3  Level 3  987540.224456

In [10]:
# 2- Qual a média do tamanho da sala de estar dos imóveis por size?
# size 0 --> Tamanho entre 0 e 1427 sqft
# size 1 --> Tamanho entre 1427 e 1910 sqft
# size 2 --> Tamanho entre 1910 e 2550 sqft
# size 3 --> Tamanho acima de R$ 2550 sqft

data['size_level'] = 'NA'

for i in range(len(data)):
    if (data.loc[i, 'sqft_living'] >= 0) & (data.loc[i, 'sqft_living'] < 1427):
        data.loc[i, 'size_level'] = 'size 0'
        
    elif (data.loc[i, 'sqft_living'] >= 1427) & (data.loc[i, 'sqft_living'] < 1910):
        data.loc[i, 'size_level'] = 'size 1'    

    elif (data.loc[i, 'sqft_living'] >= 1910) & (data.loc[i, 'sqft_living'] < 2550):
        data.loc[i, 'size_level'] = 'size 2' 
        
    else:
        data.loc[i, 'size_level'] = 'size 3'

by_size = data[['sqft_living', 'size_level']].groupby('size_level').mean().reset_index()
print(by_size)

  size_level  sqft_living
0     size 0  1123.776421
1     size 1  1661.198088
2     size 2  2202.700239
3     size 3  3318.988404

In [11]:
# 3 - Adcione as seguintes informações ao conjunto de dados original:
# Place ID: Identificação de localização
# OSM Type: Open Street Map type
# Country: Nome do País
# Country Code: Código do País

data = pd.read_csv('datasets/kc_house_data.csv')

data['place_id']     = 'NA'
data['osm_type']     = 'NA'
data['country']      = 'NA'
data['country_code'] = 'NA'

from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="geoapi_exercise")

# Make query

for i in range(10):
    query = str(data.loc[i, 'lat']) + ',' + str(data.loc[i, 'long'])
    
# API Request

    response = geolocator.reverse(query)    

# Populate Data

    if 'country_code' in response.raw['address']:
        data.loc[i, 'country_code'] = response.raw['address']['country_code']
    

    data.loc[i, 'place_id'] = response.raw['place_id']    


    data.loc[i, 'osm_type'] = response.raw['osm_type']  
    
    if 'country' in response.raw['address']:
        data.loc[i, 'country'] = response.raw['address']['country']  

data.head(5)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,place_id,osm_type,country,country_code
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,0,98178,47.5112,-122.257,1340,5650,148421265,way,United States,us
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,1991,98125,47.7210,-122.319,1690,7639,148033904,way,United States,us
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,0,98028,47.7379,-122.233,2720,8062,76736995,node,United States,us
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,0,98136,47.5208,-122.393,1360,5000,145042219,way,United States,us
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,0,98074,47.6168,-122.045,1800,7503,292831047,way,United States,us

In [12]:
# 4- Adicione os seguintes filtros no mapa:

# - Tamanho mínimo da área da sala de estar
# - Número mínimo de banheiros
# - Valor máximo do preço
# - Tamanho máximo da área do porão
# - Filtro das condições do imóvel
# - Filtro por ano de construção

data = pd.read_csv('datasets/kc_house_data.csv')

import ipywidgets as widgets
from IPython.display import display
from ipywidgets import fixed

# - Tamanho mínimo da área da sala de estar

# print(data['yr_built'].describe())

style = {'description_width':'initial'}

living_romm = widgets.IntSlider(value=800,
                                min=290,
                                max=13540,
                                step=1,
                                description='Minimum size of living room',
                                disabled=False,
                                orientation = 'horizontal')

bathroom_min = widgets.IntSlider(value=1,
                                min=0,
                                max=8,
                                step=1,
                                description='Minimum numbers of bathrooms',
                                disabled=False,
                                orientation = 'horizontal')

price_max = widgets.IntSlider(value=1e+5,
                                min= 7.500000e+04,
                                max=7.700000e+06,
                                step=1,
                                description='Maximun price',
                                disabled=False,
                                orientation = 'horizontal')

basement_size = widgets.IntSlider(value=900,
                                min= 0,
                                max=4820,
                                step=1,
                                description='Basement size',
                                disabled=False,
                                orientation = 'horizontal')

house_condition = widgets.BoundedIntText(value=2,
                                    min=0,
                                    max=5,
                                    step=1,
                                    description='House Condition',
                                    disabled=False)
year_built = widgets.IntSlider(value=2000,
                                min= 1900,
                                max=2015,
                                step=1,
                                description='Year of construction',
                                disabled=False,
                                orientation = 'horizontal')

In [13]:
# Define Map

from matplotlib import gridspec
from matplotlib import pyplot as plt
import plotly.express as px

data = pd.read_csv('datasets/kc_house_data.csv')

def updateMap(data, limit1, limit2, limit3, limit4, condition, construction):

    houses = data[(data['sqft_living'] >= limit1) & 
                  (data['bathrooms'] >= limit2) & 
                  (data['price'] <= limit3) & 
                  (data['sqft_basement'] <= limit4) & 
                  (data['condition'] >= condition) & 
                  (data['yr_built'] <= construction)][['id', 'lat', 'long', 'sqft_living', 
                                                       'bathrooms', 'price', 'sqft_basement', 'condition', 'yr_built']]


    fig = px.scatter_mapbox(houses,
                            lat = 'lat',
                            lon = 'long',
                            color = 'condition',
                            size = 'price',
                            color_continuous_scale = px.colors.cyclical.IceFire,
                            size_max=15,
                            zoom=10)

    fig.update_layout(mapbox_style = 'open-street-map')
    fig.update_layout(height=600, margin={'r':0,'t':0,'l':0,'b':0,})
    fig.show()

In [14]:
widgets.interactive(updateMap, data=fixed(data), limit1=living_romm, limit2=bathroom_min, limit3=price_max, condition=house_condition,
                    limit4=basement_size,  construction=year_built )

interactive(children=(IntSlider(value=800, description='Minimum size of living room', max=13540, min=290), Int…

In [17]:
# 5- Adicione os seguintes filtros no Dashboard:

# Filtro por data diponível para compra
# Filtro por ano de renovação
# Filtro se possui vista para a água ou não

import ipywidgets as widgets
from matplotlib import gridspec
from matplotlib import pyplot as plt
import datetime as dt
import pandas as pd
from ipywidgets import fixed
import numpy as np

# Prepare Dataset

data = pd.read_csv('datasets/kc_house_data.csv')

# Change date format

data['year'] = pd.to_datetime(data['date']).dt.strftime('%Y')
data['date'] = pd.to_datetime(data['date']).dt.strftime('%Y-%m-%d')
data['year_week'] = pd.to_datetime(data['date']).dt.strftime('%Y-%U')


# Widgets to control data

date_limit = widgets.SelectionSlider(options = data['date'].sort_values().unique().tolist(),
                                     value = '2014-12-01',
                                     description = 'Disponível',
                                     continuous_update = False,
                                     orientation = 'horizontal',
                                     readout = True)

# Widgets to control year renovated

renovated_yr = widgets.BoundedIntText(
                                    value=2010,
                                    min=1930,
                                    max=2015,
                                    step=1,
                                    description='Ano de Renovação',
                                    disabled=False)

# Widgets to control waterfront

data['is_waterfront'] = data['waterfront'].apply(lambda x:'yes' if x == 1 else 'no')

water_view = widgets.Dropdown(
                            options=data['is_waterfront'].unique().tolist(),
                            value='yes',
                            description='Waterview',
                            disabled=False)

def update_map(data, limit, option, year):
    
    # Filter data
    
    data = data[data['date']>= limit].copy()

    fig = plt.figure(figsize=(20,12)) # Configura o tamanho da figura na tela do dashboard
    specs = gridspec.GridSpec(ncols=2, nrows=2,figure=fig) # Define como o dashboard será divido na tela
    
    ax1 = fig.add_subplot(specs[0,:])  # First Row
    ax2 = fig.add_subplot(specs[1, 0])  # First Row - First Column
    ax3 = fig.add_subplot(specs[1, 1])  # Second Row - Second Column
    
    # First Graph
    
    by_year = data[['id', 'year']].groupby('year').sum().reset_index()
    ax1.bar(by_year['year'], by_year['id'])
    
    # Second Graph
    
    by_day = data[['id', 'date']].groupby('date').mean().reset_index()
    ax2.plot(by_day['date'], by_day['id'], 'go--', linewidth=1, markersize=6)
    ax2.set_title('title: Avg price by day')
    
    # Third Graph
    
    by_week_of_year = data[['id', 'year_week']].groupby('year_week').mean().reset_index()
    ax3.bar(by_week_of_year['year_week'], by_week_of_year['id'])
    ax3.set_title('title: Avg price by week of year')
    plt.xticks(rotation = 60);

In [18]:
widgets.interactive(update_map, data = fixed(data), limit=date_limit, option=water_view, year=renovated_yr )

interactive(children=(SelectionSlider(continuous_update=False, description='Disponível', index=212, options=('…

In [1]:
import ipywidgets as widgets
from matplotlib import gridspec
from matplotlib import pyplot as plt
import datetime as dt
import pandas as pd
from ipywidgets import fixed
import numpy as np

# Prepare Dataset

data = pd.read_csv('datasets/kc_house_data.csv')

for i in range(len(data)):
    if data.loc[i, 'waterfront'] == 0:
        data.loc[i, 'waterfront'] = 'No'
    else:
        data.loc[i, 'waterfront'] = 'Yes'

           id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180
1  6414100192  20141209T000000  538000.0         3       2.25         2570
2  5631500400  20150225T000000  180000.0         2       1.00          770
3  2487200875  20141209T000000  604000.0         4       3.00         1960
4  1954400510  20150218T000000  510000.0         3       2.00         1680

   sqft_lot  floors waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0         No     0  ...      7      1180.0              0
1      7242     2.0         No     0  ...      7      2170.0            400
2     10000     1.0         No     0  ...      6       770.0              0
3      5000     1.0         No     0  ...      7      1050.0            910
4      8080     1.0         No     0  ...      8      1680.0              0

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340
1      1951          1991    98125  47.7210 -122.319           1690
2      1933             0    98028  47.7379 -122.233           2720
3      1965             0    98136  47.5208 -122.393           1360
4      1987             0    98074  47.6168 -122.045           1800

   sqft_lot15
0        5650
1        7639
2        8062
3        5000
4        7503

[5 rows x 21 columns]

In [8]:
print(data['waterfront'][1000:10000])

1000    No
1001    No
1002    No
1003    No
1004    No
        ..
9995    No
9996    No
9997    No
9998    No
9999    No
Name: waterfront, Length: 9000, dtype: object